### ISSUE TITLE
Error when Autowired InboundClient on many EslEventHandler class

### ISSUE THREAD

**Issue by anhlt309** [zhouhailin/freeswitch-esl-all#2]
I has 2 class implement EslEventHandler, that is HeartbeatEslEventHandler and ReScheduleEslEventHandler. On both that EslEventHandler's subclasses include code:
@Autowired
 private InboundClient inboundClient;

So, after bean IEslEventListenerTemplate initialized, method afterPropertiesSet() got only one bean of subclass EslEventHandler.

**Comment by zhouhailin** [comment]
I can't find any errors in ReScheduleEslEventHandler, can you paste more detail error.

**Comment by anhlt309** [comment]
You can use @Autowire InboundClient in more than one class of EslEventHandler, you'll see the problem, just one or two beans of EslEventHandler's subclasses inserted in handler table.

**Comment by striveh** [comment]
@**Component** for HeartbeatEslEventHandler

**Comment by zhouhailin** [comment]
If you have solved this problem, you can submit a pr. if you have not solved the problem, paste your example, because I can't reproduce it。

**Comment by dattt01** [comment]
@anhlt309 anh liên hệ lại giúp em nhé. phongtt1925@gmail.com. anh cho em xin địa chị mail của anh để em trao đổi vụ source ạ. Em cám ơn anh.
