### ISSUE TITLE
ESL监听不到事件

### ISSUE THREAD

**Issue by ghycn** [zhouhailin/freeswitch-esl-all#22]
@EslEventName("CUSTOM verto::login")

java配置如上监听，没有任何反应

**Comment by ghycn** [comment]
> @EslEventName("CUSTOM verto::login")
> 
> java配置如上监听，没有认识反应

**Comment by zhouhailin** [comment]
你这边订阅了这个事件了么

**Comment by ghycn** [comment]
> 你这边订阅了这个事件了么， @EslEventName(CUSTOM) 就行，verto::login 通过 Event-Subclass进行判断的
> 
> 
> 
> 

那所有的CUSTOM事件都会被接收，即使有不需要监听的内容
