### ISSUE TITLE
为什么会偶尔短暂性的重新连接

### ISSUE THREAD

**Issue by wenfer** [zhouhailin/freeswitch-esl-all#27]
我的服务出现了几次事件丢失的情况，排查后发现有个onClose的日志，过了大约20秒，才重新连接上了

**Comment by zhouhailin** [comment]
> 我的服务出现了几次事件丢失的情况，排查后发现有个onClose的日志，过了大约20秒，才重新连接上了

关于重连可能，应该是tcp连接断开过，存在如下情况：
1、发送api命令时间比较长，会阻塞消息，超过了心跳时间，建议采用异步命令，不推荐关闭心跳检测
2、服务端event_socket模块重启

如果不属于上述情况，可以提供日志信息，一起排查下。
