### ISSUE TITLE
This problem occurs when running freeswitch esl spring boot starter example，how to solve it?

### ISSUE THREAD

**Issue by aini123152011** [zhouhailin/freeswitch-esl-all#29]
![image](https://user-images.githubusercontent.com/26058252/199756813-2c3b97ba-7644-43e4-8dd9-cd8a557db098.png)

This problem occurs when running freeswitch esl spring boot starter example，how to solve it?

**Comment by zhouhailin** [comment]
这个是因为本地地址不在acl里面，你可以看下fs控制台

**Comment by aini123152011** [comment]
> Your ipv4 address is rejected by ACL

my freeswitch is installed in the virtual machine, and the code is executed in the physical machine. I don't know what else to configure

**Comment by aini123152011** [comment]
<param name="apply-inbound-acl" value="lan"/>

**Comment by aini123152011** [comment]
<param name="apply-inbound-acl" value="lan"/>
