### ISSUE TITLE
link.thingscloud.freeswitch.esl.exception.InboundClientException: not found inbound handler for addr : 192.168.1.11:8021

### ISSUE THREAD

**Issue by Night-Utopia** [zhouhailin/freeswitch-esl-all#33]
我本地sping boot项目注入 inboundClient后，使用inboundClient.sendAsyncApiCommand("192.168.1.11:8021", originateCommand, null) 方式进行连接并提交，但是报错了，这是什么原因导致的

192.168.1.11是我freeswitch的地址，event_socket端口用的8021，我用telnet都是通的

**Comment by VIHATTeam** [comment]
i faced with this error too, how can you fixing it, in my case, when socket run period of time about 1-2 day, it will though this exeption , i. noticed that server able to connect to freeswitch 8021 by telnet
