### ISSUE TITLE
请问outbound被你删除了吗？

### ISSUE THREAD

**Issue by zdm2008** [zhouhailin/freeswitch-esl-all#9]

**Comment by zhouhailin** [comment]
目前在我这边实际工作中未用到Outbound，所以我就没有调整Outbound那块...

**Comment by zdm2008** [comment]
Outbound对于计费有用的，您可以把它加上吗？Inbound虽然也可以监听方式计费，但是不靠谱。

**Comment by zhouhailin** [comment]
暂时没有计划呢，如果实际过程中没有使用的话，就算上了后期有问题，也不好复现和维护呢！
另外，你指监听方式计费不靠谱能具体说明下不，分享下遇到的问题...

**Comment by zdm2008** [comment]
用Inbound连接到FS接收事件监听实现计费，它存在的问题是Inbound不会阻塞拔号，当Java ESL响应不及时（一定会发生的），不管用户账户是否余额足够，实际上这个电话已经打出去了。
当然Inbound也可以用另一种方式实现，就是用户拔号时先统一放到一个队列并放一段音乐，然后Inbound检查余额，检查条件成功则呼出PSTN落地，这样流程复杂，体验差。

**Comment by zdm2008** [comment]
Outbound它可以阻塞拔号，对于实现计费来说，实现在太简单，在拨号路由里加一段lua检查就好了，也可以用lua播放等待音乐

**Comment by zhouhailin** [comment]
@zdm2008 动态路由方式应该可以实现你的需求吧，mod_xml_curl

**Comment by zdm2008** [comment]
mod_xml_curl模块是必须的，但这个跟计费没关系

**Comment by zdm2008** [comment]
计费必须用Outbound自己实现，需求不同，没有任何现成的可用。

**Comment by zdm2008** [comment]
麻烦请把Outbound的代码加上，谢谢。
